### PR TITLE
fix(toast): fix toast icon not loading

### LINKED ISSUE #164: [Bug] - Toast doesnt load icon
**Component**
Toast

**Describe the bug**
Toast component doesn't load the state icon(tick, cross etc) based on the FDM

**To Reproduce**
Steps to reproduce the current behavior:

**Expected behavior**
A clear and concise description of what is expected to happen.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**Additional context**
Add any other context about the bug here.

### PR DESCRIPTION
**Pull request by shravan-balasubramanian**
Fix toast icon not loading

fix #164

Moved toast assets to icon assets and `<span />` to `<fw-toast />`

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My commits have standard messages as mentioned in [Contributing Guidelines](./../blob/next/CONTRIBUTING.md)

### CODE REVIEW

File: src/components/toast/toast.tsx [hunk 1]
```diff
@@ -38,6 +38,11 @@ export class Toast {
    */
   @State() fadeOut = false;
 
+  /**
+   * State icon size
+   */
+  @State() stateIconSize = 14;
```
Comment (asifahmedfw) [inline src/components/toast/toast.tsx:44]:
```suggestion
  @State() iconSize = 14;
```

**Review by asifahmedfw — CHANGES_REQUESTED** [review]

**Review by asifahmedfw — APPROVED** [review]
